---
services:
  main:
    image: docker.io/dmotte/portfwd-server-rootless:latest
    build: build
    restart: always
    network_mode: bridge
    ports: ["2222:2222"]
    volumes:
      - ssh-host-keys:/ssh-host-keys
      - ./ssh-client-keys:/ssh-client-keys
    environment:
      PERMIT_OPEN: 10.0.2.15:8001 10.0.2.15:8002 10.0.2.2:8003

volumes:
  ssh-host-keys: {}
